spring:
  application:
    name: cine8-back
  datasource:
    url: "jdbc:postgresql://localhost:5432/cine8"
    username: postgres
    password: Luismanuel13
    driver-class-name: org.postgresql.Driver
